import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import useLogout from "../hooks/useLogout";

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }
    return { props };
  },
  sessionOptions
);

export default function Home(props) {
  const router = useRouter();
  const logout = useLogout();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />

      <main className={styles.homePage}>
        <br />
        <h1 className={styles.welcomeTitle}>
          Welcome to 
        </h1>
        <h1 className={styles.logoTitle}>Prose Pal!</h1>
        <br />

        <p className={styles.appDescription}>
          Prose Pal is an app designed to help avid readers and writers discover and track words.
          Readers and writers are constantly coming across new words that may pique their 
          interest in one way or another – even if it's by making them think, "What does 
          that word mean?"
        </p>
        <p className={styles.appDescription}>
          With Prose Pal, you can search for words and learn about their meanings, definitions,
          and parts of speech. You can also view their synonyms and antonyms! If you want to
          remember a word for later, you can add it to your vocabulary list and view its definitions,
          synoyms, and more later.
        </p>
        
        <br />
        <br />

        <div className={styles.grid}>
          {props.isLoggedIn ? (
            <>
              <Link href="/search" className={styles.card}>
                <h2>Word Search &rarr;</h2>
              </Link>
            </>
          ) : (
            <>
              <Link href="/login" className={styles.homeButtons}>
                <h2>Login &rarr;</h2>
              </Link>

              <Link href="/signup" className={styles.homeButtons}>
                <h2>Sign up &rarr;</h2>
              </Link>
            </>
          )}
        </div>
        <br />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
